[build]
  command = "cd SkillEdge-AI && npm install && npm run build"
  publish = "SkillEdge-AI/.next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

# Required environment variables
[build.environment]
  DATABASE_URL = "postgresql://postgres:SkillEdge-AI@db.uzcipgmeuqilktbwodls.supabase.co:5432/postgres"
  NEXT_PUBLIC_SUPABASE_URL = "https://uzcipgmeuqilktbwodls.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV6Y2lwZ21ldXFpbGt0YndvZGxzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTU4OTY0MzEsImV4cCI6MjAzMTQ3MjQzMX0.7a4MiGxVuC1sVMxY0vKdLOOOKP5IVIKcxC0PIc8jz8Y"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Handle Next.js routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true 